[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = fastled/FastLED@^3.6.0
board_build.filesystem = littlefs
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_mode = dio
extra_scripts = post:merge_bin.py